leafly_url: https://www.leafly.com/dispensary-info/detroit-grass-station/menu
wp_url: https://leaflywp.justinvieira.com
consumer_key: ck_my_wordpress_consumer_key
consumer_secret: cs_my_wordpress_consumer_secret